use acon;
insert into acon.exchange_rate value(1, 1393.6, default, default, 'dollar');
insert into acon.nation values(default, 'ko', 1, null);
insert into acon.nation values(default, 'ja', 1, 1);
insert into acon.nation values(default, 'en', 1, 1);
insert into acon.nation values(default, 'cn', 1, 1);
insert into acon.nation values(default, 'tw', 1, 1);
insert into acon.nation values(default, 'vi', 1, 1);
insert into acon.nation values(default, 'th', 1, 1);
insert into acon.nation values(default, 'es', 1, 1);
insert into acon.nation values(default, 'fr', 1, 1);
insert into acon.nation values(default, 'id', 1, 1);
insert into acon.nation values(default, 'ru', 1, 1);
insert into acon.nation values(default, 'de', 1, 1);
insert into acon.nation values(default, 'it', 1, 1);
insert into acon.nation values(default, 'unkown_country', 0, 1);

insert into acon.buyer values (default, 'testBuyerKr', 'testBuyer@buyer.kr', '1234', default, default, 1);
insert into acon.buyer values (default, 'testBuyerJa', 'testBuyer@buyer.ja', '1234', default, default, 2);
insert into acon.buyer values (default, 'testBuyeren', 'testBuyer@buyer.en', '1234', default, default, 3);
insert into acon.buyer values (default, 'testBuyercn', 'testBuyer@buyer.cn', '1234', default, default, 4);
insert into acon.buyer values (default, 'testBuyertw', 'testBuyer@buyer.tw', '1234', default, default, 5);
insert into acon.buyer values (default, 'testBuyervi', 'testBuyer@buyer.vi', '1234', default, default, 6);
insert into acon.buyer values (default, 'testBuyerth', 'testBuyer@buyer.th', '1234', default, default, 7);
insert into acon.buyer values (default, 'testBuyeres', 'testBuyer@buyer.es', '1234', default, default, 8);
insert into acon.buyer values (default, 'testBuyerfr', 'testBuyer@buyer.fr', '1234', default, default, 9);
insert into acon.buyer values (default, 'testBuyerid', 'testBuyer@buyer.id', '1234', default, default, 10);
insert into acon.buyer values (default, 'testBuyerru', 'testBuyer@buyer.ru', '1234', default, default, 11);
insert into acon.buyer values (default, 'testBuyerde', 'testBuyer@buyer.de', '1234', default, default, 12);
insert into acon.buyer values (default, 'testBuyerit', 'testBuyer@buyer.it', '1234', default, default, 13);
insert into acon.editor values (default, 'testEditor', 'testEditor@editor.com', '1234', default, default);
insert into acon.author values (default, 'testAuthor', 'testAuthor@author.com', '1234', default, default);